### PR TITLE
Adding BERT 101 blog post

### PR DESCRIPTION
**Pull request by feconroses**
## What does this PR do?

Adds a new blog post "BERT 101" by @BritneyMuller. The [draft on Google Docs](https://docs.google.com/document/d/1bNeGtZH0LTnY-fXSbR7z2kszisxKDv_ATFzlr_X1y28/edit?usp=sharing) was reviewed by Omar, Patrick, me and others. 

This post is the second of the 2 SEO experiments we will be doing with Britney in the short term. With these tests, we want to validate our ability to rank in the top positions of Google for relevant keywords by following current SEO best practices.

## Screenshot
BERT 101 - State Of The Art NLP Model Explained (4)

### CODE REVIEW

**Comment by feconroses** [comment]
> Looks great! Only thing I spot is the crossed out text in the second paragraph of 2.1 ?
> 
> Other than that 👍

Nice catch, I escaped the 'strikethrough' markdown character, now this paragraph looks as expected: 

Screen Shot 2022-03-01 at 1 05 57 PM

**Comment by feconroses** [comment]
@osanseviero awesome!! Squashed and merged! @BritneyMuller amazing job 👏👏👏

**Comment by julien-c** [comment]
only reading this post now but this is quite cool!

**Comment by BritneyMuller** [comment]
Thank you so much @julien-c @feconroses & @osanseviero 🙏  Seems to be doing quite well in terms of engagement too (5+mins average read time with 12k+ views) 🎉 ❤️

**Pull request merged**
