### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by stavares843**
- Fix typos

### CODE REVIEW

**Comment by julien-c** [comment]
Hi @stavares843, thanks! can you split your changes in two different PRs, ie. keep this one just for the types and open another one for the GitHub Action? 🙏

**Comment by stavares843** [comment]
will do 🔨

**Comment by stavares843** [comment]
updated 🎉 will add the action in other PR 🔨

**Review by julien-c — APPROVED** [review]
LGTM, thanks!

**Comment by stavares843** [comment]
https://github.com/huggingface/blog/pull/745

**Pull request merged**
