### PR TITLE
[ray-tune] Update Ray Tune blog post examples to be runnable

### PR DESCRIPTION
**Pull request by matthewdeng**
The example code in this blog post will result in errors due to a combination of breaking API changes and missing dependencies. This change allows the user to run the code successfully on a clean environment (with or without GPUs).

**Changes:**

1. Update pip installation packages to include all required dependencies.
2. Replace deprecated `evaluate_during_training` parameter with `evaluation_strategy`.
3. Remove  `n_jobs` which is not supported in the Ray integration.
4. Add `metric`/`mode` to `search_alg`/`scheduler`. **Note:** We can also update `run_hp_search_ray` to pass these directly into `tune.run` as an optimization.
5. Refresh modified links.

### CODE REVIEW

**Review by richardliaw — APPROVED** [review]
Looks good!

**Comment by richardliaw** [comment]
cc @patrickvonplaten  @sgugger could you help merge this patch?

**Review by sgugger — APPROVED** [review]
LGTM, thanks for the fixes.

I'll leave the actual merge to @julien-c or @Pierrci since there is some deploy to do afterward, I believe.

**Comment by julien-c** [comment]
Deployed at https://huggingface.co/blog/ray-tune 🙏

**Pull request merged**
