### PR TITLE
01_how_to_train.ipynb: Fix TypeError

### PR DESCRIPTION
**Pull request by orestisfl**
`prediction_loss_only` should go to `TrainingArguments`

### CODE REVIEW

**Comment by harsham05** [comment]
@orestisfl Thanks for fixing this, what is the purpose of setting `prediction_loss_only` equal to True while training a language model from scratch?

**Comment by ZakMiller** [comment]
Any reason this isn't merged? The colab linked [here](https://huggingface.co/blog/how-to-train) is broken.

**Comment by julien-c** [comment]
@sgugger looks good to me, can you give it a quick look and merge if it's right?

**Comment by sgugger** [comment]
Yes, that argument was removed from the main `Trainer` in v4 (it's a `TrainingArgument` now but shouldn't be necessary since not `compute_metrics` is passed).

Thanks for fixing!

**Pull request merged**
