### PR TITLE
Fix katex formulas from nystrom

### PR DESCRIPTION
**Pull request by osanseviero**
@novice03 does this look good?

* align -> aligned
* Added some missing spaces
* I did not get softmax to be perfect, but I think this works

### CODE REVIEW

**Comment by osanseviero** [comment]
I'll merge this but let me know if something was missing :)

**Comment by novice03** [comment]
Yes, this is much better. Thank you for your help!

**Comment by osanseviero** [comment]
Thank you @novice03 for your amazing contribution! Would you like to share it in social media?

**Comment by novice03** [comment]
Yes @omarespejel I've made a LinkedIn post [here](https://www.linkedin.com/posts/pranav-pulijala-6b2122192_nystr%C3%B6mformer-approximating-self-attention-activity-6960267132534222848-F9vN?utm_source=linkedin_share&utm_medium=member_desktop_web).

**Pull request merged**
