### PR TITLE
constrained beam search thumbnail fix

### PR DESCRIPTION
**Pull request by cwkeam**
fixes thumbnail issue for #232 @osanseviero @patrickvonplaten

### CODE REVIEW

**Comment by cwkeam** [comment]
@osanseviero do you know why the thumbnail still isn't being displayed in the website by any chance?

**Comment by osanseviero** [comment]
Hey there! We haven't done a deploy yet, we usually avoid Friday night deploys. This will be fixed later today

**Comment by cwkeam** [comment]
@osanseviero oh alright sounds good!

**Comment by osanseviero** [comment]
This is deployed now! :rocket:

**Comment by patrickvonplaten** [comment]
Thank you!

**Pull request merged**
