### PR TITLE
Update llama2 for non engineers

### PR DESCRIPTION
**Pull request by VioletteLepercq**

### CODE REVIEW

**Comment by VioletteLepercq** [comment]
@osanseviero can you approve this ? Thanks in advance

**Comment by pcuenca** [comment]
@VioletteLepercq let me help you with that :)

**Review by VioletteLepercq — COMMENTED** [review]
thankss

**Comment by pcuenca** [comment]
@VioletteLepercq let me know if that's ok. The process is:

- Get your images and run them through an image optimizer, which reduces file size with no impact on quality. I use ImageOptim (screenshot below), but there are many online. This provides faster load times for our users, especially those with poor connections.
- Upload to a folder in documentation-images/blog.
- Link to the download url for each file.

Screenshot 2023-09-29 at 10 18 59

**Comment by VioletteLepercq** [comment]
many thanks @pcuenca 🙏

**Review by pcuenca — APPROVED** [review]

**Pull request merged**
