### PR TITLE
interns-23 -> interns-2023

### PR DESCRIPTION
**Pull request by LysandreJik**
Addressing https://github.com/huggingface/blog/pull/667/files#r1036023545

### CODE REVIEW

**Review by osanseviero — APPROVED** [review]
Or maybe just interns? We can always update next year when we have new internships

**Comment by LysandreJik** [comment]
Superseded by https://github.com/huggingface/blog/pull/672#pullrequestreview-1199645668

**Comment by LysandreJik** [comment]
No strong opinions, having 2023 means that the link will forever be good as no rename will need to happen!

**Comment by osanseviero** [comment]
But also we'll have a very soon outdated site that I'm not sure has much value to keep after 6 months :) no strong opinion for sure

**Pull request closed without merging**
