### PR TITLE
Fix html & latex

### PR DESCRIPTION
**Pull request by mishig25**
There were some small errors regarding HTML & latex

### CODE REVIEW

**Review by osanseviero — APPROVED** [review]
Thanks for this!

**Comment by julien-c** [comment]
wow how did you catch those?

**Comment by mishig25** [comment]
@julien-c I have a branch where blog gets compiled through mdsvex rather than lib/Markdown.ts
And these errors were discovered

**Comment by julien-c** [comment]
(deployed)

**Pull request merged**
