### PR TITLE
TGI Kubernetes Cluster.dev 

### PR DESCRIPTION
**Pull request by voatsap**
Spend a few weeks on this )
Created a Hugging Face chart, stackTemplates, tested many times for few users.
Should be useful for community!

### CODE REVIEW

**Comment by julien-c** [comment]
maybe @nsarrazin wants to take a quick look, would this content be interesting in the hf.co/blog ? or better to publish in community blogs?

**Comment by julien-c** [comment]
(@voatsap if you prefer, you can publish in community blogs by joining this org: https://huggingface.co/blog-explorers)

**Comment by julien-c** [comment]
@voatsap Ok so after a quick glance we do think the blogpost would be better suited to https://huggingface.co/blog-explorers

**Comment by voatsap** [comment]
@julien-c @nsarrazin thanks for routing me to the community blogs, I have published it here:
https://huggingface.co/blog/voatsap/tgi-kubernetes-cluster-dev
Will close PR tomorrow if no other comments will follow.

**Comment by voatsap** [comment]
Closed as it published inside community blogs

**Pull request closed without merging**
