### PR TITLE
Point to PR with IPO fix

### PR DESCRIPTION
**Pull request by lewtun**
Adds a clarifying remark about the root cause of the bug and a pointer to the TRL PR so the community understands better what changed.

### CODE REVIEW

**Review by edbeeching — APPROVED** [review]
Thanks @lewtun , LGTM

**Review by kashif — APPROVED** [review]

**Comment by lifengjin** [comment]
Just curious (and also slightly confused): where in paper does it mention that the loss needs to be averaged across tokens?

**Comment by JubilantJerry** [comment]
I'm also confused about this claim that the loss needs to be averaged. Page 7 of https://arxiv.org/pdf/2310.12036.pdf clearly shows that the IPO loss is defined based on $\pi(y \mid x)$, matching their notation on page 3 for their recap on the DPO loss. I didn't see them formally define $\pi(y|x)$, but I'm pretty sure it needs to be interpreted as a probability of a sequence. The log of the probability of a sequence can be found by summing the log probability of each token, but not by taking the average of those token probabilities, the average has no meaningful interpretation. Unless I missed something from the paper?

**Comment by lewtun** [comment]
> @lifengjin The summed operation makes the constant regularization / beta depend on the length of the response. Averaged can fix it.

Indeed this is what the DeepMind authors pointed out to us in the initial version of the blog post. I don't believe it is explicitly mentioned in the paper, which is why we overlooked this detail

**Pull request merged**
