### PR TITLE
Update quanto-diffusers.md

### PR DESCRIPTION
**Pull request by tolgacangoz**
Great blog post!

[I might be wrong; isn't the latest stable release of `torch` `2.4.0`?](https://pypi.org/project/torch/#history)

### CODE REVIEW

**Comment by pcuenca** [comment]
The authors may have used a pre-release version for the tests cc @sayakpaul @dacorvo

**Review by sayakpaul — APPROVED** [review]

**Comment by sayakpaul** [comment]
You are right.

**Comment by tolgacangoz** [comment]
This PR is complete now.

I am looking forward to seeing (more) quantizations from the field of LLMs!

**Comment by sayakpaul** [comment]
LLM.int8 experiments are here: https://github.com/huggingface/diffusers/discussions/8746

**Comment by sayakpaul** [comment]
Thanks for your contributions!

**Comment by tolgacangoz** [comment]
Thanks for merging!

**Pull request merged**
