### PR TITLE
fix the last formula in infini-attention.md

### PR DESCRIPTION
**Pull request by yaoqih**
transalte format from latex to follow.

### CODE REVIEW

**Comment by pcuenca** [comment]
Thanks @yaoqih!

I also noticed this one, but I can't see the problem in the markdown:

Screenshot 2024-08-29 at 09 28 20

**Comment by yaoqih** [comment]
> Thanks @yaoqih!
> 
> I also noticed this one, but I can't see the problem in the markdown:
> 
> Screenshot 2024-08-29 at 09 28 20
Wow, you are really attentive. I carefully compared the English and Chinese versions, and the formulas are exactly the same. However, the Chinese version is missing a space before the formula. I'm not familiar with the embedding rules for follow and markdown formulas; do I need to add a space before the formula?"
image

**Comment by pcuenca** [comment]
Strange, I see the space in the Chinese version as well ` \\( N \\) 是查询的数量，\\( d_{\text {key }} \\) 是每个查询的维度。`. Not sure what's going on, but feel free to add it and see if it solves it!

**Comment by yaoqih** [comment]
I guess I need to add spaces before the formula so that the formula can be separated and recognized correctly. I have added spaces. Please try again.

**Comment by pcuenca** [comment]
It worked :) Thanks @yaoqih 🙌

**Pull request merged**
