### PR TITLE
Elaborated on RL4LMs

### PR DESCRIPTION
**Pull request by rajcscw**
- Added detailed information on RL4LMs

### CODE REVIEW

**Comment by rajcscw** [comment]
@natolambert  Nice work on this RLHF post!  I just proposed minor changes elaborating RL4LMs.

**Comment by natolambert** [comment]
Hi @rajcscw -- thanks for the PR. I just changed formatting a little and added similar info about TRLX that you added to RL4LMs. Sorry about getting the acronym wrong to start, that was my mistake. If you're happy with the suggestions, I'll commit and merge them.

**Comment by rajcscw** [comment]
@natolambert All good! I don't see the proposed changes (are they in this PR or in another). In any case, if they are just formatting changes, should be okay to merge.

**Review by natolambert — CHANGES_REQUESTED** [review]
Oops, I forgot to click submit on the review @rajcscw.

**Review by natolambert — APPROVED** [review]
LGTM - merging.

**Pull request merged**
