### PR TITLE
Add: zh/moe.md

### PR DESCRIPTION
**Pull request by cauyxy**
Add chinese translation of [Mixture of Experts Explained](https://huggingface.co/blog/moe).

### CODE REVIEW

**Comment by cauyxy** [comment]
@chenglu @xianbaoqian @adeenayakup Hi Luke, Tiezhen and Adeena, could you please help check and merge this blog translation PR? Thanks! 🌹 🤗

**Comment by cauyxy** [comment]
Hi @osanseviero , do you know someone who can review and merge this PR? Thanks!🌹 🤗

**Comment by pcuenca** [comment]
Hi @cauyxy, thanks a lot for your contribution. The people you first mentioned should be able to help, just give it a few days.

**Comment by xianbaoqian** [comment]
Hi @cauyxy Sry didn't see your PR early. Great work! Thanks for the contribution! 

Could you please submit the pull request to https://github.com/huggingface-cn/hf-blog-translation? Our folks will conduct a review, primarily by @zhongdongy, and then the pull request will be squashed and merged in this repository.

PS: I have just sent you a request on WeChat. We have a group of translation volunteers, and we would like to extend an invitation to you to join us. :-)

**Pull request closed without merging**
