### PR TITLE
Change title for SEO + add EAP CTA to "Customer Service with Hugging Face" blog post

### PR DESCRIPTION
**Pull request by feconroses**
Following up on our conversation [here](https://github.com/huggingface/blog/pull/273), this PR makes some minor adjustments to the [Supercharged Customer Service with Hugging Face](https://huggingface.co/blog/supercharge-customer-service-with-nlp) blog post:
- Adjust the title for SEO.
- Adds an EAP CTA at the end of the blog post.
- Other minor adjustments (e.g. most of @nbroad1881 suggestions).

@patrickvonplaten @nbroad1881 added you as "reviewers" in case you want to check this out. If you don't have the time for the review, don't worry, I can merge+deploy without a review as it's a simple PR (plan to do this at the end of the week).

### CODE REVIEW

**Review by patrickvonplaten — APPROVED** [review]

**Comment by julien-c** [comment]
Note that there's no automated redirect for the updated URL (no big deal i think)

**Comment by feconroses** [comment]
@julien-c thanks for flagging! @BritneyMuller also noticed this and we discussed this last Friday. IMO not a big deal. Brit was going to see how we can add this redirect manually, and if it doesn't require too much time/effort, she would do it.

**Comment by julien-c** [comment]
we usually it fairly easily in https://github.com/huggingface/conf/blob/master/moonrise/nginx-moonrise.conf

(but i don't think that's a big deal – it's more for broken links on the Web but likely not that many for this post – on Google side they can usually detect it's a renamed page and update their index)

**Comment by feconroses** [comment]
@julien-c thanks for the context! It seems easy/straightforward @BritneyMuller want to give it a try in a new PR?

**Comment by BritneyMuller** [comment]
> @julien-c thanks for the context! It seems easy/straightforward @BritneyMuller want to give it a try in a new PR?

Done: https://github.com/huggingface/conf/pull/176

**Pull request merged**
