### PR TITLE
Update ph blog

### PR DESCRIPTION
**Pull request by Michellehbn**
gh light theme

gh dark theme

### CODE REVIEW

**Review by VioletteLepercq — COMMENTED** [review]
👍

**Review by jeffboudier — APPROVED** [review]
Can we fix readability of green background (make it dark grey) in dark mode?
Other than that lgtm

**Comment by Michellehbn** [comment]
I haven't been able to make the background color grey in dark mode yet, it's not rendering when I check in codespaces 😭, will check with @gary149 to see what I'm missing! we can merge this PR and fix later if needed too

**Review by julien-c — APPROVED** [review]

**Review by gary149 — APPROVED** [review]
image

**Review by Michellehbn — COMMENTED** [review]
thank you @gary149 !

**Pull request merged**
