### PR TITLE
Add reformer notebook

### PR DESCRIPTION
**Pull request by patrickvonplaten**
Adds Reformer blog post

### CODE REVIEW

**Comment by julien-c** [comment]
should this be in github.com/huggingface/notebooks instead?

**Comment by julien-c** [comment]
Ooops too late I guess :-/

**Comment by patrickvonplaten** [comment]
Will have to update the notebook, the latex equations are not rendered nicely: https://huggingface.co/blog/reformer

**Comment by patrickvonplaten** [comment]
Actually, the same is true for the generate blog post: https://huggingface.co/blog/how-to-generate

**Pull request merged**
