### PR TITLE
Fixing the date of Concrete ML post.

### PR DESCRIPTION
**Pull request by bcm-at-zama**
as requested in https://github.com/huggingface/blog/pull/1885#issuecomment-2059133887 by @pcuenca

### CODE REVIEW

**Review by pcuenca — APPROVED** [review]

**Comment by pcuenca** [comment]
I don't know why the post is not rendering, maybe because the date was wrong initially? If so, we can wait until tomorrow if it fixes automatically. Any other ideas @mishig25?

**Comment by pcuenca** [comment]
@bcm-at-zama the first line must be `---`. So the Markdown file should start with:

```
---
title: "Running Privacy-Preserving Inferences on Hugging Face Endpoints"
thumbnail: /blog/assets/fhe-endpoints/thumbnail.png
authors:
- user: binoua
  guest: true
---
```

**Comment by bcm-at-zama** [comment]
Sorry let me fix that

**Comment by bcm-at-zama** [comment]
done in https://github.com/huggingface/blog/pull/1999

**Pull request merged**
