### PR TITLE
Update command line in `bridgetower.md`

### PR DESCRIPTION
**Pull request by regisss**
See https://huggingface.slack.com/archives/C02V51Q3800/p1700731200774629 for more information.

### CODE REVIEW

**Comment by regisss** [comment]
Gently pinging @osanseviero @pcuenca for review

**Review by pcuenca — APPROVED** [review]

**Comment by pcuenca** [comment]
Are you planning to update the code to use the `bytes` property instead of `path`? (Just out of curiosity)

**Comment by regisss** [comment]
> Are you planning to update the code to use the `bytes` property instead of `path`? (Just out of curiosity)

Yes (if possible because not sure it goes along well with Habana's API)! But not now because I have quite a lot on my plate at the moment :grimacing:

**Comment by pcuenca** [comment]
Haha, of course!

**Pull request merged**
